version: '3'

services:
    nginx-proxy:
        image: nginx
        container_name: nginx_proxy_container
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx_config_content/nginx.conf:/etc/nginx/nginx.conf:ro
        restart: always

    wordpress-cont:
      image: wordpress
      ports:
          - 8080:80
      environment:
          WORDPRESS_DB_PASSWORD: example
      restart: always

    mysql:
      image: mysql:5.7
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: example

    wordpress_backup:
        build: ./backup_content
        container_name: wordpress_backup_container
        volumes:
            - .:/root/backup_content
        restart: always