version: '3'

services:
    nginx:
        image: nginx
        links:
            - wordpress
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx_config_content/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./wordpress:/var/www/html
            - ./letsencrypt/archive/www.theenk.io/fullchain1.pem:/etc/nginx/fullchain1.pem:ro
            - ./letsencrypt/archive/www.theenk.io/privkey1.pem:/etc/nginx/privkey1.pem:ro
        restart: always

    wordpress:
        image: wordpress:4.9.2-php7.0-fpm
        links:
            - wp_db:mysql
        volumes:
            - ./wordpress:/var/www/html
        environment:
            WORDPRESS_DB_PASSWORD: "aqwe123"
        restart: always

    wp_db:
        image: mariadb
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "aqwe123"
        restart: always
